name: Delpoy

on:
  push:
    branches:
      - master
    paths:
      - "service/**"

defaults:
  run:
    working-directory: service

jobs:
  delpoy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew installDist
      - name: Deloy to Huawei ECS
        uses: cross-the-world/ssh-scp-ssh-pipelines@latest
        with:
          host: ${{ secrets.HUAWEI_HOST }}
          user: ${{ secrets.HUAWEI_USER }}
          pass: ${{ secrets.HUAWEI_PASS }}
          scp: |
            ./service/build/install/service/** => /root/service/
          last_ssh: |
            sh /root/service/run.sh
