name: Github Publish

on:
  pull_request:
    paths-ignore:
      - "service/**"
  push:
    paths-ignore:
      - "service/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: enriikke/gatsby-gh-pages-action@v2
        env:
          NODE_OPTIONS: --max-old-space-size=8192
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          deploy-branch: gh-pages
